common:
  - pkg/**/*
  - test/**/*
  - openapi/templates/**/*
  - scripts/**/*
kafka:
  - internal/kafka/**/*
  - openapi/kas*
  - cmd/kas*
  - templates/**/*
  - Dockerfile
  - config/**/*
  - docker/**/*
connector:
  - internal/connector/**/*
  - openapi/connector*
github:
  - .github/**/*
api-change:
  - openapi/kas*
connector-api-change:
  - openapi/connector*
documentation:
  - docs/**/*
  - "*.md"
service-template:
  - templates/**/*
  - Dockerfile
