#This configuration file contains information about each Kafka instance types, dynamic scaling configuration
#
#The following properties must be defined for each instance types compute node configuration:
#   - max_compute_nodes: the maximum number of nodes needed to create an appropriate machine pool with the configuration needed by the autoscaler

---
developer:
  compute_nodes_config:
    max_compute_nodes: 3
standard:
  compute_nodes_config:
    max_compute_nodes: 9
