#This configuration file contains information about each Kafka instance types, the pre-warming configuration
#
#The following properties must be defined for each Kafka instance type:
#   - reserved_streaming_units: the number of streaming unit reservations to be made on each data plane cluster. If set to zero, no pre-warming applied on the cluster
#   - base_streaming_unit_size: the base streaming unit size as defined in the supported types. In most cases it is "x1" which is the default if not defined.   

---
developer:
  reserved_streaming_units: 0 # no pre-warming
  base_streaming_unit_size: x1 
standard:
  reserved_streaming_units: 0 # no pre-warming
  base_streaming_unit_size: x1
